#!/bin/zsh
#>[what]
#   1. collect dirs from the last 10 commits,
#   2. search for broken links within dirs
#   3. remove broken links
#/[what]

emulate -LR zsh
setopt errexit dotglob
IFS=
autoload -Uz log-msg
configs=${1:-$HOME/projects/configs}

: ${HOME:?HOME must be set}

function delete_broken_links {
  local root=$1 ; log-msg -t delete-broken-links -- $root

  typeset -aU dirs broken
  # 1. 10 last refs -> all dirs
  for ref ( ${(@f)$(git rev-list -10 HEAD)} ) {
    dirs+=( ${(@f)$(git ls-tree -dr --name-only $ref)} )
  }

  # 2. dirs -> dirs with at least 2 parts #[why] reducing search radius
  dirs=( ${(M)dirs:#*/?*} ) # [what] (M) keep matches, pattern: path with atleast one non trailing slash

  # 3. dirs -> OS dirs; HOME/<rest> -> $HOME/<rest>, else /<rest>
  local -a os_dirs
  for dir ( $dirs ) {
    [[ $dir == HOME/* ]] && os_dirs+=$HOME/${dir#HOME/} || os_dirs+=/$dir
  }
  dirs=( $os_dirs )

  # 4. dirs -> broken links (ignore our *.bk backups)
  for dir ( $dirs ) {
    broken+=( $dir/*(-@N) )
  }
  broken=( ${broken:#*.bk} )

  # 5. broken links -> trash

  if (( $#broken )) { rm $broken ; log-msg -t rm -- $broken }
}

pushd $configs/root
delete_broken_links root
popd
