#!/bin/zsh
#>[what]
#   1. search for all *.host.auto.tmpl templates
#   2. render it on the host
#/[what]

emulate -LR zsh
IFS=
setopt errexit
autoload -Uz log-msg

configs=${1:-/Users/ko/projects/configs}
t_ext='.host.auto.tmpl'

pushd $configs/root-ln

#[what] . - regular files, D - GLOB_DOT opt (search hidden)
for template ( **/*${t_ext}(.D) ) {
  #[what] % - strip non greedy from the end
  render_to=/${template%${t_ext}}
  gomplate -f "$template" -o "$render_to" ; log-msg -t gomplate -- $render_to
}

popd
