# yaml-language-server: $schema=https://gitlab.com/konradodwrot/go-modules/-/raw/main/che/assets/data/che.schema.json
##[>] 🤖🤖
options:
  profileWorkingDirectory: .

dev/infra/terraform:
  include:
    runScripts:
      - scripts/01-install-terraform.zsh
##[<] 🤖🤖
