#[≟] 1st file sourced

disable log #[∵] this builtin would shadow /usr/bin/log binary

export ZDOTDIR=${HOME}/.config/zsh #[∵] so $ZDOTDIR/.zshenv (user config, PATH) loads next 🤖🤖

#[……] env
setopt allexport

EDITOR='vim'
VISUAL='vim'
LANG='C.UTF-8'
LC_COLLATE='C.UTF-8'
LC_CTYPE='C.UTF-8'
LC_MESSAGES='C.UTF-8'
LC_NUMERIC='C.UTF-8'
LC_TIME='C.UTF-8'
AWS_DEFAULT_OUTPUT='json'
CLOUDSDK_CORE_DEFAULT_FORMAT='json'
AZURE_CORE_OUTPUT='json'
GOMPLATE_CONFIG='/etc/gomplate/gomplate.yaml'
PKG_CONFIG_PATH='/opt/homebrew/opt/ruby/lib/pkgconfig'
PIP_DISABLE_PIP_VERSION_CHECK='1'
RIPGREP_CONFIG_PATH='/etc/rg/rgrc'
SSH_ASKPASS='/usr/local/scripts/shell/s-rt-ssh-askpass-op'
SSH_ASKPASS_REQUIRE='force'
MANPAGER='/usr/bin/less -Is'
WHATISPAGER='/usr/bin/less -Is'

unsetopt allexport
#[⫶⫶] env


#[……] ANSI escape sequences
#[⌖] https://ecma-international.org/wp-content/uploads/ECMA-48_5th_edition_june_1991.pdf
typeset -A rt_seq=(
    esc         $'\u001B'    #[≟] ANSI -> ESC: introducer for escape sequences
    csi         $'\u001B['   #[≟] ANSI -> CSI: Control Sequence Introducer
    dcs         $'\u0090'    #[≟] ANSI -> DCS: Device Control String

    goto-col-1  $'\u001B[1G' #[≟] ANSI -> CHA: cursor to column 1 of the current row
    goto-row-1  $'\u001B[H'  #[≟] ANSI -> CUP: cursor to row 1, column 1
)
#[⫶⫶] ANSI escape sequences


. /etc/zsh/zshenv.d/fn-loaders.zsh

typeset -a funcs=(
    /etc/zsh/zshenv.d/functions
)

fn-rt-insert fpath $funcs
fn-rt-autoload-functions $funcs
fn-rt-source /etc/zsh/zshenv.d/auto.d
