#[≟] 1st file sourced

disable log #[∵] this builtin would shadow /usr/bin/log binary

#[……] env
#[…] xdg defaults
typeset -A xdg_default_locations=(
    XDG_BIN_HOME        "${HOME}/.local/bin"                #[≟] xdg - bin recommendation
    XDG_CACHE_HOME      "${HOME}/.cache"                    #[≟] user-specific non-esseintial data
    XDG_CONFIG_HOME     "${HOME}/.config"                   #[≟] user-specific configuration files
    XDG_DATA_HOME       "${HOME}/.local/share"              #[≟] user-specific data files
    XDG_LOCAL_HOME      "${HOME}/.local"
    XDG_STATE_HOME      "${HOME}/.local/state"              #[≟] user-specific state data
)
for k v in "${(@kv)xdg_default_locations}"; export "$k=$v"
#[⫶] xdg defaults

typeset -A env_vars=(
    EDITOR              "vim"
    VISUAL              "vim"
    LANG                "C.UTF-8"
    LC_COLLATE          "C.UTF-8"
    LC_CTYPE            "C.UTF-8"
    LC_MESSAGES         "C.UTF-8"
    LC_NUMERIC          "C.UTF-8"
    LC_TIME             "C.UTF-8"
    GOPATH              "${HOME}/go"
    ASDF_DATA_DIR       "${XDG_STATE_HOME}/asdf"
    ASDF_CONFIG_FILE    "${XDG_CONFIG_HOME}/asdf/.asdfrc"
    AZURE_CONFIG_DIR    "${XDG_CONFIG_HOME}/azure"

    #[≟] cloud cli default output format
    AWS_DEFAULT_OUTPUT           "json"
    CLOUDSDK_CORE_DEFAULT_FORMAT "json"
    AZURE_CORE_OUTPUT            "json"
    GOMPLATE_CONFIG     "/etc/gomplate/gomplate.yaml"
    PKG_CONFIG_PATH     "/opt/homebrew/opt/ruby/lib/pkgconfig"
    PYENV_ROOT          "${HOME}/.pyenv"
    PIP_DISABLE_PIP_VERSION_CHECK "1"
    RIPGREP_CONFIG_PATH "/etc/rg/rgrc"

    #[≟] 1Password ssh passphrase helper
    SSH_ASKPASS         "/usr/local/scripts/shell/s-rt-ssh-askpass-op"
    SSH_ASKPASS_REQUIRE "force"

    #[∵] defining man env vars allows overriding, man.conf values cannot be overridden
    MANPAGER            "/usr/bin/less -Is"
    WHATISPAGER         "/usr/bin/less -Is"
)
for k v in "${(@kv)env_vars}"; export "$k=$v"

unset env_vars
#[⫶⫶] env


#[……] ANSI escape sequences
#[⌖] https://ecma-international.org/wp-content/uploads/ECMA-48_5th_edition_june_1991.pdf
typeset -A rt_seq=(
    esc         $'\u001B'    #[≟] ANSI -> ESC: introducer for escape sequences
    csi         $'\u001B['   #[≟] ANSI -> CSI: Control Sequence Introducer
    dcs         $'\u0090'    #[≟] ANSI -> DCS: Device Control String

    goto-col-1  $'\u001B[1G' #[≟] ANSI -> CHA: cursor to column 1 of the current row
    goto-row-1  $'\u001B[H'  #[≟] ANSI -> CUP: cursor to row 1, column 1
)
#[⫶⫶] ANSI escape sequences


typeset -U fpath=(
    /etc/zsh/zshenv.d/functions
    /opt/homebrew/share/zsh/site-functions
    ${fpath}
)

#[≟] autoload zshenv.d functions (all shells)
for f in /etc/zsh/zshenv.d/functions/*(N:t); {
  emulate zsh -LRc "autoload $f"
}

#[≟] source zshenv.d/auto.d files (all shells) in ascending by name order
for rc in /etc/zsh/zshenv.d/auto.d/*.zsh(Non); {
  . $rc
}
