#[≟] 5th zsh file sourced, after $ZDOTDIR/.zprofile; only for interactive shells

#[…] set params
typeset -U path=(
    ${XDG_BIN_HOME}
    ${GOPATH}/bin
    ${PYENV_ROOT}/bin
    ${ASDF_DATA_DIR}/shims
    /usr/local/go/bin
    /usr/local/bin
    /usr/local/scripts/shell
    /usr/local/scripts/installs
    /usr/local/scripts/python
    /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Support
    /opt/local/bin
    /opt/X11/bin
    /opt/homebrew/share/google-cloud-sdk/bin
    /opt/homebrew/lib/ruby/gems/*/bin(N)
    /opt/homebrew/opt/ruby/bin
    /opt/homebrew/bin
    /usr/bin
    /usr/sbin
    /bin
    /sbin
    ${path}
)
typeset -U fpath=(
    /etc/zsh/zshrc.d/functions
    /etc/zsh/zshrc.d/completions
    ${fpath}
)
#[⫶] set params

#[…] plug-in files
#[≟] autoload zshrc.d functions (interactive)
for f in /etc/zsh/zshrc.d/functions/*(N:t); {
  emulate zsh -LRc "autoload $f"
}

#[≟] source zshrc.d/auto.d files in ascending by name order
for rc in /etc/zsh/zshrc.d/auto.d/*.zsh(Non); {
  . $rc
}

fn-rt-load-static-history
#[⫶] plug-in files
