#[≟] 5th zsh file sourced, after $ZDOTDIR/.zprofile; only for interactive shells

#[…] set params
typeset -U path=(
    ${XDG_BIN_HOME}
    ${GOPATH}/bin
    ${PYENV_ROOT}/bin
    ${ASDF_DATA_DIR}/shims
    /usr/local/go/bin
    /usr/local/bin
    /usr/local/scripts/shell
    /usr/local/scripts/installs
    /usr/local/scripts/python
    /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Support
    /opt/local/bin
    /opt/X11/bin
    /opt/homebrew/share/google-cloud-sdk/bin
    /opt/homebrew/lib/ruby/gems/*/bin(N)
    /opt/homebrew/opt/ruby/bin
    /opt/homebrew/bin
    /usr/bin
    /usr/sbin
    /bin
    /sbin
    ${path}
)

typeset -U fpath=(
    ${XDG_CONFIG_HOME}/zsh/functions
    ${XDG_STATE_HOME}/zsh/completions
    /etc/zsh/functions
    /etc/zsh/completions
    /opt/homebrew/share/zsh/site-functions
    ${fpath}
)
#[⫶]

#[…] plug-in files

#[≟] source all files from zsh/rc.d in ascending by name order
for rc in /etc/zsh/rc.d/*.zsh(on); {
  . $rc
}

#[≟] load functions
for f in /etc/zsh/functions/**(:t); {
  emulate zsh -LRc "autoload $f"
}

fn-rt-load-static-history
#[⫶]
