workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  auto_cancel:
    on_new_commit: interruptible

stages:
  - validate
  - dry-run
  - test

.base:
  needs: []
  image: python:3.14-slim
  ##[>] 🤖🤖
  variables:
    GO_VERSION: "1.26.3"
    GOMODCACHE: $CI_PROJECT_DIR/.cache/go-mod
    GOCACHE: $CI_PROJECT_DIR/.cache/go-build
  cache:
    key:
      files:
        - ci/go/go.sum
    paths:
      - .cache/go-mod
      - .cache/go-build
  ##[<] 🤖🤖
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends make git zsh curl ca-certificates clang
    - pip install --no-cache-dir -r root/etc/python/requirements.txt
    - curl -fsSL https://github.com/hairyhenderson/gomplate/releases/download/v5.1.0/gomplate_linux-amd64 -o /usr/local/bin/gomplate
    - chmod +x /usr/local/bin/gomplate
    - curl -fsSL https://github.com/mikefarah/yq/releases/download/v4.53.3/yq_linux_amd64 -o /usr/local/bin/yq
    - chmod +x /usr/local/bin/yq
    ##[>] 🤖🤖
    - curl -fsSL https://go.dev/dl/go$GO_VERSION.linux-amd64.tar.gz | tar -C /usr/local -xz
    - export PATH=/usr/local/go/bin:$PATH
    - export CC=clang
    ##[<] 🤖🤖

validate-docsgen:
  extends: .base
  stage: validate
  script:
    - make run-repo-ci-render-templates RENDER_LOCAL=
    - git diff --exit-code

validate-typecheck:
  extends: .base
  stage: validate
  script:
    - make run-repo-ci-typecheck

dry-run-sync:
  extends: .base
  stage: dry-run
  parallel:
    matrix:
      - CHE_FORCE_PROFILE: [desktop/macos, cli/macos, cli/linux]
  script:
    - MK_DRY_RUN=all make run-sync-full

test-scripts:
  extends: .base
  stage: test
  script:
    - make run-repo-ci-tests

.e2e-macos:
  #[why] macos remote vms have minimum lease time of 24h, I don't need 24/7 instance running so my local machine polls gitlab pipeline, executes the job and sends results back
  tags: [local]
  image: macos-tahoe-vanilla-base
  resource_group: macos-local-vm
  interruptible: true  #[what] new commits will cancel this job to free up resource 🤖
  variables:
    GIT_CLONE_PATH: $CI_BUILDS_DIR/configs

dry-run-sync-desktop-macos-local-vm:
  extends: .e2e-macos
  stage: dry-run
  needs: []
  script:
    - MK_DRY_RUN=all make run-sync


sync-macos-local-vm:
  extends: .e2e-macos
  stage: test
  needs: [dry-run-sync-desktop-macos-local-vm]
  rules:
    - if: $CI_MERGE_REQUEST_DRAFT == "true"
      when: never
    - when: on_success
  script:
    - make run-sync
