#[⌖] $ man 1 direnv.toml

[global]
#[≟] enable .env loading, not just .envrc
load_dotenv = true

#[≟] .envrc file loading must succeed, otherwise fire error
strict_env = true

#[≟] fire warning if .envrc loading is slow
warn_timeout = "300ms"

#[≟] "-" disables normal logging (loading/unloading); errors still show (default "$name: %s")
log_format = "-"

#[≟] (default) hide the "export +VAR" diff line on directory entry
hide_env_diff = false

[whitelist]

#[≟] trust projects having the prefix without asking
prefix = ["~/projects/ko"]
