#[where] $ man 1 direnv.toml

[global]
#[what] enable .env loading, not just .envrc
load_dotenv = true

#[what] .envrc file loading must succeed, otherwise fire error
strict_env = true

#[what] fire warning if .envrc loading is slow
warn_timeout = "300ms"

#[what]  hide the "export +VAR" diff line on directory entry
hide_env_diff = true

[whitelist]

#[what] trust projects having the prefix without asking
prefix = ["~/projects/ko"]
