# yaml-language-server: $schema=https://gitlab.com/konradodwrot/unrestricted/go-modules/-/raw/main/che/assets/data/che.schema.json
##[>] 🤖🤖
options:
  profileWorkingDirectory: root

observability/grafana:
  options: {runIf: ['builtin:isOs == macos', 'builtin:isVirt == false']}
  include:
    makeLinks:
      - etc/**
    makeCopies:
      - owner: root
        ownerGroup: "0"
        chmod: "0644"
        files:
          - {source: Library/LaunchDaemons/grafana.plist.ontoHost.cp, dest: [/Library/LaunchDaemons/grafana.plist]}
    makeDirs:
      - chmod: "2775"
        directories:
          - {dest: [/var/log/grafana]}
          - {dest: [/usr/local/var/grafana]}
##[<] 🤖🤖
