#>[⌖]
# https://prometheus.io/docs/prometheus/latest/configuration/configuration/
#/[⌖]

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  query_log_file: /var/log/prometheus/queries.log

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          app: "prometheus"

  - job_name: "otelcol"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:8889"]
        labels:
          app: "otelcol"

  - job_name: "otelcol-internal"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:8888"]
        labels:
          app: "otelcol"

  - job_name: "listening-ports"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9101"]
        labels:
          app: "port_exporter"

  - job_name: "dir-sizes"
    scrape_interval: 60s
    static_configs:
      - targets: ["localhost:9102"]
        labels:
          app: "dir_size_exporter"

  - job_name: "loki"
    static_configs:
      - targets: ["localhost:3100"]
        labels:
          app: "loki"

  - job_name: "jaeger"
    static_configs:
      - targets: ["localhost:8890"]
        labels:
          app: "jaeger"

  - job_name: "grafana"
    static_configs:
      - targets: ["localhost:9300"]
        labels:
          app: "grafana"
