#!/usr/bin/env sh
hooks_dir="$(dirname "$0")/pre-commit.rc.d"
has_error=0

for hook in "$hooks_dir"/*; do
    [ -f "$hook" ] || continue
    . "$hook"
    result=$?
    [ $result -ne 0 ] && has_error=$result
done

exit $has_error
