##[>] 🤖🤖
validateSpec: error
packages:
  updateCheck:
    enabled: true
    cooldown: 15m
  completions:
    zsh:
      enabled: true
      installDestinationCandidates: ~/.local/state/zsh/completions
otel:
  enabled: true
  endpoint: localhost:4317
  protocol: grpc
  metrics: true
  logs: true
##[<] 🤖🤖
