##[>] 🤖🤖
validateSpec: error
packages:
  source:
    url:
    ref:
  autoUpdate:
    enabled: true
    if:
      refIsLatest:
        cooldown: 0s
      dryRunIsTrue:
        enabled: true
  completions:
    zsh:
      enabled: true
      installDestinationCandidates: ~/.local/state/zsh/completions
otel:
  enabled: true
  endpoint: localhost:4317
  protocol: grpc
  metrics: true
  logs: true
##[<] 🤖🤖
