#!/bin/sh
#>[what]
#   generate directory tree in yaml format
#   excludes top level hidden dirs
#   includes hidden nested dirs
#/[what]

set -e

JQ_FILTER='
def sortkey:
  if type == "object" then (keys[0]) else . end;

def convert:
  if .contents then { (.name): [.contents[] | convert] | sort_by(sortkey) }
  else .name
  end;

[.[] | convert] | sort_by(sortkey) | add
'

#>[what] tree options
#   --noreport   omit the file/directory count footer
#   -d           list directories only
#   -a           include nested hidden dirs
#   --gitignore  prune paths matched by repo .gitignore / .git/info/exclude
#   -J           output JSON
#   */           glob that grabs top-level non-hidden directories
#/[what]
cat <<'EOF'
#[what] Repository directory tree. Autogenerated by root-ln/usr/local/scripts/shell/s-root-generate-yaml-dir-tree.
EOF

tree --noreport -da -J --gitignore -- */ \
  | jq "${JQ_FILTER}" \
  | yq --prettyPrint
