#!/bin/bash

set -e

configs=${1:-/Users/ko/projects/configs}

#[≟] scan only ./root/**
for top in "$configs"/root/*/; do
  find "/${top#"$configs"/root/}" -type l -lname "$configs/*" ! -exec test -e {} \; -print -delete 2>/dev/null || true
done
