package render

// [>] 🤖🤖

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	onepassword "github.com/1password/onepassword-sdk-go"
	"github.com/hairyhenderson/gomplate/v4"
)

// opRetryDelays: backoff between op-resolve attempts that hit a vault rate limit.
var opRetryDelays = []time.Duration{
	500 * time.Millisecond,
	1 * time.Second,
	2 * time.Second,
}

// isRateLimit: 1Password SDK surfaces vault rate limiting only in the error text.
func isRateLimit(err error) bool {
	return err != nil && strings.Contains(err.Error(), "rate limit exceeded")
}

// retry runs op, re-running while shouldRetry(err) holds, sleeping the matching
// delay before each retry. Stops after len(delays) retries or first non-retryable result.
func retry[T any](delays []time.Duration, sleep func(time.Duration), shouldRetry func(error) bool, op func() (T, error)) (T, error) {
	v, err := op()
	for _, d := range delays {
		if !shouldRetry(err) {
			break
		}
		sleep(d)
		v, err = op()
	}
	return v, err
}

// Exec renders body via the gomplate library. env is a gomplate built-in; op resolves
// op:// references through the 1Password Go SDK (service-account token). name: error messages only.
func Exec(name string, body []byte) ([]byte, error) {
	ctx := context.Background()
	funcs := template.FuncMap{"op": opResolver(ctx)}
	r := gomplate.NewRenderer(gomplate.RenderOptions{Funcs: funcs, MissingKey: "error"})
	var buf bytes.Buffer
	if err := r.Render(ctx, filepath.Base(name), string(body), &buf); err != nil {
		return nil, fmt.Errorf("render template %s: %w", name, err)
	}
	return buf.Bytes(), nil
}

// opResolver returns an op(ref) template func that lazily inits one 1Password client
// (OP_SERVICE_ACCOUNT_TOKEN) on first use and reuses it for the render's references.
// Resolves retry on vault rate-limit errors.
func opResolver(ctx context.Context) func(string) (string, error) {
	var client *onepassword.Client
	return func(ref string) (string, error) {
		if client == nil {
			token := os.Getenv("OP_SERVICE_ACCOUNT_TOKEN")
			if token == "" {
				return "", fmt.Errorf("op %q: OP_SERVICE_ACCOUNT_TOKEN unset", ref)
			}
			c, err := onepassword.NewClient(ctx,
				onepassword.WithServiceAccountToken(token),
				onepassword.WithIntegrationInfo("che", "1.0.0"),
			)
			if err != nil {
				return "", fmt.Errorf("op client: %w", err)
			}
			client = c
		}
		secret, err := retry(opRetryDelays, time.Sleep, isRateLimit, func() (string, error) {
			return client.Secrets().Resolve(ctx, ref)
		})
		if err != nil {
			return "", fmt.Errorf("op resolve %q: %w", ref, err)
		}
		return secret, nil
	}
}

// ResolveAtIncludes inlines '@path' lines as repoRoot/<path> contents, '~/' -> root/HOME/. Port of fn-tpl-inline-includes.
func ResolveAtIncludes(repoRoot string, body []byte) []byte {
	var out bytes.Buffer
	for line := range strings.Lines(string(body)) {
		line = strings.TrimSuffix(line, "\n")
		if IsAtInclude(line) {
			path := strings.TrimPrefix(line, "@")
			if rest, ok := strings.CutPrefix(path, "~/"); ok {
				path = "root/HOME/" + rest
			}
			if content, err := os.ReadFile(filepath.Join(repoRoot, path)); err == nil {
				out.Write(bytes.TrimRight(content, "\n"))
				out.WriteByte('\n')
				continue
			}
		}
		out.WriteString(line)
		out.WriteByte('\n')
	}
	return out.Bytes()
}

// HasSecretRef: body contains an op:// secret reference (a render-time vault fetch).
func HasSecretRef(body []byte) bool {
	return bytes.Contains(body, []byte("op://"))
}

// IsAtInclude: line is exactly '@<no-space>', no whitespace.
func IsAtInclude(line string) bool {
	if !strings.HasPrefix(line, "@") || len(line) < 2 {
		return false
	}
	return !strings.ContainsAny(line, " \t")
}

// Header: autogen comment by extension. Port of fn-tpl-make-header.
func Header(out, tmplPath string) string {
	if strings.HasSuffix(out, ".md") {
		return fmt.Sprintf("<!-- autogenerated using %s -->", tmplPath)
	}
	return fmt.Sprintf("# autogenerated using %s", tmplPath)
}

// [<] 🤖🤖
