package render

// [>] 🤖🤖

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"

	"gopkg.in/yaml.v3"
)

// Exec runs body through text/template with the host+repo FuncMap. name is used
// only for error messages.
func Exec(name string, body []byte) ([]byte, error) {
	t, err := template.New(filepath.Base(name)).
		Option("missingkey=error").
		Funcs(funcMap()).
		Parse(string(body))
	if err != nil {
		return nil, fmt.Errorf("parse template %s: %w", name, err)
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, nil); err != nil {
		return nil, fmt.Errorf("render template %s: %w", name, err)
	}
	return buf.Bytes(), nil
}

// funcMap reproduces the gomplate namespaces the host templates call (env/op).
func funcMap() template.FuncMap {
	return template.FuncMap{
		"env": func() envNS { return envNS{} },
		"op":  opRead,
	}
}

type envNS struct{}

func (envNS) Getenv(key string) string { return os.Getenv(key) }

// opRead shells to `op read --no-newline <ref>` (same as the gomplate op plugin).
func opRead(ref string) (string, error) {
	out, err := exec.Command("op", "read", "--no-newline", ref).Output()
	if err != nil {
		return "", fmt.Errorf("op read %q: %w", ref, err)
	}
	return string(out), nil
}

// ResolveAtIncludes inlines '@path' lines as the contents of repoRoot/<path>;
// '~/' -> root/HOME/. Port of fn-tpl-inline-includes.
func ResolveAtIncludes(repoRoot string, body []byte) []byte {
	var out bytes.Buffer
	for line := range strings.Lines(string(body)) {
		line = strings.TrimSuffix(line, "\n")
		if IsAtInclude(line) {
			path := strings.TrimPrefix(line, "@")
			if rest, ok := strings.CutPrefix(path, "~/"); ok {
				path = "root/HOME/" + rest
			}
			if content, err := os.ReadFile(filepath.Join(repoRoot, path)); err == nil {
				out.Write(bytes.TrimRight(content, "\n"))
				out.WriteByte('\n')
				continue
			}
		}
		out.WriteString(line)
		out.WriteByte('\n')
	}
	return out.Bytes()
}

// IsAtInclude: a line that is exactly '@<no-space>' with no whitespace.
func IsAtInclude(line string) bool {
	if !strings.HasPrefix(line, "@") || len(line) < 2 {
		return false
	}
	return !strings.ContainsAny(line, " \t")
}

// Header: autogen comment by extension. Port of fn-tpl-make-header.
func Header(out, tmplPath string) string {
	if strings.HasSuffix(out, ".md") {
		return fmt.Sprintf("<!-- autogenerated using %s -->", tmplPath)
	}
	return fmt.Sprintf("# autogenerated using %s", tmplPath)
}

// SplitFrontmatter returns (frontmatterYAML, body) from a '---\n...\n---\n' doc.
func SplitFrontmatter(src []byte) (fm, body []byte) {
	rest := src[len("---\n"):]
	if i := bytes.Index(rest, []byte("\n---\n")); i >= 0 {
		return rest[:i+1], rest[i+len("\n---\n"):]
	}
	if i := bytes.Index(rest, []byte("\n---")); i >= 0 {
		return rest[:i+1], rest[i+len("\n---"):]
	}
	return nil, src
}

// FlexList unmarshals a YAML scalar or sequence into []string (render-to flatten).
type FlexList []string

func (f *FlexList) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind == yaml.ScalarNode {
		*f = FlexList{value.Value}
		return nil
	}
	var xs []string
	if err := value.Decode(&xs); err != nil {
		return err
	}
	*f = xs
	return nil
}

// HasFrontmatter reports whether src opens with a '---\n' frontmatter block.
func HasFrontmatter(src []byte) bool { return bytes.HasPrefix(src, []byte("---\n")) }

// [<] 🤖🤖
