package render

// [>] 🤖🤖

import (
	"strings"
	"testing"

	"configs/ci/go/packages/che/internal/testutil"
)

func TestHeader(t *testing.T) {
	if got := Header("/x/y.md", "tmpl"); got != "<!-- autogenerated using tmpl -->" {
		t.Errorf("md header = %q", got)
	}
	if got := Header("/x/config.toml", "tmpl"); got != "# autogenerated using tmpl" {
		t.Errorf("default header = %q", got)
	}
}

func TestResolveAtIncludes(t *testing.T) {
	dir := t.TempDir()
	testutil.WriteTree(t, dir, map[string]string{
		"root/HOME/.config/agents/docs/comments.md": "INCLUDED\n",
	})
	out := ResolveAtIncludes(dir, []byte("before\n@~/.config/agents/docs/comments.md\nafter\n"))
	got := string(out)
	if !strings.Contains(got, "INCLUDED") || !strings.Contains(got, "before") || !strings.Contains(got, "after") {
		t.Errorf("at-include resolution = %q", got)
	}
	if strings.Contains(got, "@~") {
		t.Errorf("at-include line not replaced: %q", got)
	}
}

func TestIsAtInclude(t *testing.T) {
	cases := map[string]bool{
		"@~/.config/x":  true,
		"@path/to/file": true,
		"@ has space":   false,
		"text @middle":  false,
		"plain":         false,
		"@":             false,
	}
	for line, want := range cases {
		if got := IsAtInclude(line); got != want {
			t.Errorf("IsAtInclude(%q) = %v, want %v", line, got, want)
		}
	}
}

// [<] 🤖🤖
