package render

// [>] 🤖🤖

import (
	"errors"
	"strings"
	"testing"
	"time"

	"configs/ci/go/packages/che/internal/testutil"
)

func TestHeader(t *testing.T) {
	if got := Header("/x/y.md", "tmpl"); got != "<!-- autogenerated using tmpl -->" {
		t.Errorf("md header = %q", got)
	}
	if got := Header("/x/config.toml", "tmpl"); got != "# autogenerated using tmpl" {
		t.Errorf("default header = %q", got)
	}
}

func TestResolveAtIncludes(t *testing.T) {
	dir := t.TempDir()
	testutil.WriteTree(t, dir, map[string]string{
		"root/HOME/.config/agents/docs/comments.md": "INCLUDED\n",
	})
	out := ResolveAtIncludes(dir, []byte("before\n@~/.config/agents/docs/comments.md\nafter\n"))
	got := string(out)
	if !strings.Contains(got, "INCLUDED") || !strings.Contains(got, "before") || !strings.Contains(got, "after") {
		t.Errorf("at-include resolution = %q", got)
	}
	if strings.Contains(got, "@~") {
		t.Errorf("at-include line not replaced: %q", got)
	}
}

func TestIsAtInclude(t *testing.T) {
	cases := map[string]bool{
		"@~/.config/x":  true,
		"@path/to/file": true,
		"@ has space":   false,
		"text @middle":  false,
		"plain":         false,
		"@":             false,
	}
	for line, want := range cases {
		if got := IsAtInclude(line); got != want {
			t.Errorf("IsAtInclude(%q) = %v, want %v", line, got, want)
		}
	}
}

func TestIsRateLimit(t *testing.T) {
	cases := map[error]bool{
		errors.New("performing a vault operation: rate limit exceeded"): true,
		errors.New("op resolve: secret not found"):                      false,
		nil: false,
	}
	for err, want := range cases {
		if got := isRateLimit(err); got != want {
			t.Errorf("isRateLimit(%v) = %v, want %v", err, got, want)
		}
	}
}

func TestRetry(t *testing.T) {
	rateLimit := errors.New("rate limit exceeded")
	delays := []time.Duration{1, 1, 1}

	t.Run("succeeds first try, no sleep", func(t *testing.T) {
		slept := 0
		calls := 0
		v, err := retry(delays, func(time.Duration) { slept++ }, isRateLimit,
			func() (string, error) { calls++; return "ok", nil })
		if v != "ok" || err != nil || calls != 1 || slept != 0 {
			t.Errorf("v=%q err=%v calls=%d slept=%d", v, err, calls, slept)
		}
	})

	t.Run("retries rate limit then succeeds", func(t *testing.T) {
		slept := 0
		calls := 0
		v, err := retry(delays, func(time.Duration) { slept++ }, isRateLimit,
			func() (string, error) {
				calls++
				if calls < 3 {
					return "", rateLimit
				}
				return "ok", nil
			})
		if v != "ok" || err != nil || calls != 3 || slept != 2 {
			t.Errorf("v=%q err=%v calls=%d slept=%d", v, err, calls, slept)
		}
	})

	t.Run("exhausts retries, returns last error", func(t *testing.T) {
		calls := 0
		_, err := retry(delays, func(time.Duration) {}, isRateLimit,
			func() (string, error) { calls++; return "", rateLimit })
		if !errors.Is(err, rateLimit) || calls != len(delays)+1 {
			t.Errorf("err=%v calls=%d, want %d", err, calls, len(delays)+1)
		}
	})

	t.Run("non-retryable error fails immediately", func(t *testing.T) {
		other := errors.New("bad ref")
		calls := 0
		_, err := retry(delays, func(time.Duration) {}, isRateLimit,
			func() (string, error) { calls++; return "", other })
		if !errors.Is(err, other) || calls != 1 {
			t.Errorf("err=%v calls=%d, want 1", err, calls)
		}
	})
}

// [<] 🤖🤖
