package main

// [>] 🤖🤖🤖

import (
	"os"
	"strings"
	"testing"
)

func TestSplitFrontmatter(t *testing.T) {
	src := []byte("---\nrender-to:\n  - ~/.config/claude/CLAUDE.md\n---\nbody line\n")
	fm, body := splitFrontmatter(src)
	if !strings.Contains(string(fm), "render-to") {
		t.Errorf("frontmatter missing render-to: %q", fm)
	}
	if strings.TrimSpace(string(body)) != "body line" {
		t.Errorf("body = %q, want 'body line'", body)
	}
}

func TestExecTemplateEnv(t *testing.T) {
	t.Setenv("HOME", "/Users/test")
	a := &app{}
	out, err := a.execTemplate("t", []byte(`log_dir = "{{ env.Getenv "HOME" }}/x"`))
	if err != nil {
		t.Fatal(err)
	}
	if string(out) != `log_dir = "/Users/test/x"` {
		t.Errorf("env render = %q", out)
	}
}

func TestTmplHeader(t *testing.T) {
	if got := tmplHeader("/x/y.md", "tmpl"); got != "<!-- autogenerated using tmpl -->" {
		t.Errorf("md header = %q", got)
	}
	if got := tmplHeader("/x/config.toml", "tmpl"); got != "# autogenerated using tmpl" {
		t.Errorf("default header = %q", got)
	}
}

func TestResolveAtIncludes(t *testing.T) {
	dir := t.TempDir()
	if err := os.MkdirAll(dir+"/root/HOME/.config/agents/docs", 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(dir+"/root/HOME/.config/agents/docs/comments.md", []byte("INCLUDED\n"), 0644); err != nil {
		t.Fatal(err)
	}
	a := &app{repoRoot: dir}
	out := a.resolveAtIncludes([]byte("before\n@~/.config/agents/docs/comments.md\nafter\n"))
	got := string(out)
	if !strings.Contains(got, "INCLUDED") || !strings.Contains(got, "before") || !strings.Contains(got, "after") {
		t.Errorf("at-include resolution = %q", got)
	}
	if strings.Contains(got, "@~") {
		t.Errorf("at-include line not replaced: %q", got)
	}
}

func TestIsAtInclude(t *testing.T) {
	cases := map[string]bool{
		"@~/.config/x":  true,
		"@path/to/file": true,
		"@ has space":   false,
		"text @middle":  false,
		"plain":         false,
		"@":             false,
	}
	for line, want := range cases {
		if got := isAtInclude(line); got != want {
			t.Errorf("isAtInclude(%q) = %v, want %v", line, got, want)
		}
	}
}

// [<] 🤖🤖🤖
