receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
      http:
        endpoint: localhost:4318

  hostmetrics:
    collection_interval: 5s
    scrapers:
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
      load:
      memory:
        metrics:
          system.memory.utilization:
            enabled: true
      disk:
      filesystem:
        metrics:
          system.filesystem.utilization:
            enabled: true
      network:
      paging:
      process:
        mute_process_exe_error: true
        mute_process_user_error: true
        mute_process_io_error: true
        metrics:
          process.cpu.utilization:
            enabled: true
          process.memory.utilization:
            enabled: true

processors:
  memory_limiter:
    check_interval: 5s
    limit_mib: 4000
    spike_limit_mib: 500

extensions:
  health_check:
    endpoint: localhost:13133
  zpages:
    endpoint: 0.0.0.0:55679

exporters:
  prometheus:
    endpoint: localhost:8889
    resource_to_telemetry_conversion:
      enabled: true
  otlphttp/loki:
    endpoint: http://localhost:3100/otlp
  otlp/jaeger:
    endpoint: 127.0.0.1:4327
    tls:
      insecure: true


service:
  extensions: [health_check, zpages]
  pipelines:
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [memory_limiter]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [memory_limiter]
      exporters: [otlphttp/loki]
    traces:
      receivers: [otlp]
      processors: [memory_limiter]
      exporters: [otlp/jaeger]
