# Workspace subgroup

Generated map of this subgroup: its directory structure, each repo's purpose
inlined, child subgroups inlined recursively. Regenerated by the `configs`
repo's `gitlab/projects` clone-and-index profile. See [configs](https://gitlab.com/konradodwrot/configs).

@assets/data/repo-index.md
