#!/bin/sh
#>[≟]
#   install asdf managed tools
#/[≟]

set -e

plugins='
terraform https://github.com/asdf-community/asdf-hashicorp.git
kubectl   https://github.com/asdf-community/asdf-kubectl.git
kubectx   https://gitlab.com/wt0f/asdf-kubectx.git
pnpm      https://github.com/jonathanmorley/asdf-pnpm.git
'

echo "$plugins" | while read -r name url; do
    [ -n "$name" ] || continue
    sudo asdf plugin add "$name" "$url"
done

asdf install  #[≟] install versions of tools from .tool-versions
