#!/bin/zsh
#>[what]
#   generate each subgroup's repo-index + rendered AGENTS.md/CLAUDE.md for every
#   subgroup dir under $WORKSPACE_DIR (the workspace root down through all groups)
#/[what]

emulate -LR zsh
setopt errexit pipefail
umask 002

##[>] 🤖🤖🤖
#[why] environments without the render-files toolchain (image bakes) skip
if ! (( $+commands[render-repo-group-index] )) {
  print -r -- "index: skip: render-repo-group-index not found"
  return 0
}

#[why] gate on the same vars as 10-clone: no token/group -> the clone was skipped, so there is nothing on disk to index
if [[ -z ${GITLAB_TOKEN-} ]] {
  print -r -- "index: skip: GITLAB_TOKEN unset"
  return 0
}
if [[ -z ${GITLAB_GROUPS-} && -z ${GITLAB_GROUP-} ]] {
  print -r -- "index: skip: no group in GITLAB_GROUPS/GITLAB_GROUP"
  return 0
}

#[what] the top index lists each group's host dir, then every subgroup below
typeset root=${WORKSPACE_DIR:-$HOME/projects/gitlab}
typeset tpl=${0:A:h}/../templates/subgroup-index.md.ontoRepo.tpl

#[why] render-repo-group-index owns discovery; here we drive one binary per subgroup
function has_repo_below {
  local hits=($1/.git(N/) $1/**/.git(N/))
  (( $#hits ))
}

function inline_index {
  local dir=$1 body=$2
  print -r -- $body | while IFS= read -r line; do
    if [[ $line == '@assets/data/repo-index.md' ]]; then
      cat ${dir}/assets/data/repo-index.md
    else
      print -r -- $line
    fi
  done
}

function index_subgroup {
  local dir=$1
  local data=${dir}/assets/data
  local header="<!-- autogenerated using profiles/gitlab/projects/templates/subgroup-index.md.ontoRepo.tpl -->"
  mkdir -p $data
  #[what] repo-index.md: this subgroup's direct children (repos inlined, child subgroups linked)
  render-repo-group-index $dir > ${data}/repo-index.md
  #[why] cwd = dir so the template's readBody/@ resolve there
  local body=$( cd $dir && render-tpl -f $tpl )
  print -r -- $header > ${dir}/CLAUDE.md
  print -r -- $body >> ${dir}/CLAUDE.md
  print -r -- $header > ${dir}/AGENTS.md
  inline_index $dir $body >> ${dir}/AGENTS.md
  print -r -- "index: $dir"
}

function walk {
  local dir=$1
  [[ -d $dir/.git ]] && return 0
  local child is_subgroup=0
  for child in $dir/*(N/); do
    if { has_repo_below $child } { is_subgroup=1; walk $child }
  done
  (( is_subgroup )) && index_subgroup $dir
}

walk $root
##[<] 🤖🤖🤖
