kitty_mod ctrl+shift

map kitty_mod+cmd+left neighboring_window left
map kitty_mod+cmd+right move_window right
map kitty_mod+cmd+down neighboring_window down
map kitty_mod+cmd+up move_window up

env ZDOTDIR=${HOME}/.config/zsh
