# clipboard
copy_on_select yes
clipboard_max_size 512
clipboard_max_size 0
clipboard_control write-clipboard write-primary read-clipboard-ask read-primary-ask

# shell
shell_integration enabled
env ZDOTDIR=${HOME}/.config/zsh

# font
font_size 14.0
font_family      family="Source Code Pro"
bold_font        auto
italic_font      auto
bold_italic_font auto

# bell
enable_audio_bell no
window_alert_on_bell no
macos_dock_badge_on_bell no

# misc
confirm_os_window_close 0
remember_window_position yes
auto_reload_config 0.1

# key bindings
kitty_mod ctrl+shift

map kitty_mod+cmd+left neighboring_window left
map kitty_mod+cmd+right move_window right
map kitty_mod+cmd+down neighboring_window down
map kitty_mod+cmd+up move_window up
map cmd+w no_op
map cmd+c no_op
