#[⌖] $ man 5 kitty.conf

#[…] clipboard
copy_on_select no
clipboard_max_size 512
clipboard_max_size 0
clipboard_control write-clipboard write-primary read-clipboard-ask read-primary-ask
#[⫶] clipboard

#[…] shell
shell_integration enabled
env ZDOTDIR=${HOME}/.config/zsh
#[⫶] shell

#[…] font
font_size 14.0
font_family      family="Source Code Pro"
bold_font        auto
italic_font      auto
bold_italic_font auto
#[⫶] font

#[…] bell
enable_audio_bell no
window_alert_on_bell no
macos_dock_badge_on_bell no
#[⫶] bell

#[…] misc
confirm_os_window_close 0
remember_window_position yes
auto_reload_config 0.1
#[⫶] misc

#[…] key bindings
kitty_mod ctrl+shift

map kitty_mod+cmd+left neighboring_window left
map kitty_mod+cmd+right move_window right
map kitty_mod+cmd+down neighboring_window down
map kitty_mod+cmd+up move_window up
map cmd+t no_op
map cmd+w close_window
map cmd+q>q quit
map cmd+r no_op
map cmd+enter no_op

map backspace      send_text all \x08
map alt+backspace  send_text all \u0017
map cmd+backspace  send_text all \u0015

map cmd+z          send_text all \u0090z
map cmd+shift+z    send_text all \u0090Z
map cmd+x          send_text all \u0090x

map cmd+up         send_text all \u0090U
map cmd+down       send_text all \u0090D

map alt+left       send_text all \u001bb
map alt+right      send_text all \u001bf
map alt+up         send_text all \u001bp
map alt+down       send_text all \u001bn
map cmd+left       send_text all \u0001
map cmd+right      send_text all \u0005

map alt+delete     send_text all \u001bd
map alt+z          send_text all \u001bz
map cmd+delete     send_text all \u0090K
#[⫶] key bindings

