#!/bin/zsh
#>[≟]
#   1. collect dirs from the last 10 commits,
#   2. search for broken links within dirs
#   3. remove broken links
#/[≟]

emulate -LR zsh
setopt errexit dotglob
IFS=
configs=${1:-/Users/ko/projects/configs}

function delete_broken_links {
  local root=$1 ; log-msg -t delete-broken-links -- $root

  typeset -aU dirs broken
  # 1. 10 last refs -> all dirs
  for ref ( ${(@f)$(git rev-list -10 HEAD)} ) {
    dirs+=( ${(@f)$(git ls-tree -dr --name-only $ref)} )
  }

  # 2. dirs -> dirs with at least 2 parts #[∵] reducing search radius
  dirs=( ${(M)dirs:#*/?*} ) # [≟] (M) keep matches, pattern: path with atleast one non trailing slash

  # 3. dirs -> OS dirs
  dirs=( /${^dirs} )

  # 4. dirs -> broken links
  for dir ( $dirs ) {
    broken+=( $dir/*(-@N) )
  }

  # 5. broken links -> trash

  if (( $#broken )) { rm $broken ; log-msg -t rm -- $broken }
}

for root ( root-{ln,cp} ) {
  pushd $configs/$root
  delete_broken_links $root
  popd
}
