#!/bin/zsh

emulate -LR zsh
setopt errexit

if (( EUID != 0 )) { print -u2 "must run as root"; exit 1 }

typeset configs configs_owner home
typeset -a dirs_user_space dirs_system_space dirs_system_space_world

function mk_dirs {
  local -a owner perms
  local dir
  zparseopts -D -E -owner:=owner -perms:=perms
  for dir ( $@ ) {
    if [[ ! -d $dir ]] {
      mkdir -p $dir ; print "mkdir: $dir"
      if (( $#owner )) { chown -R $owner[2] $dir; print "chown: $dir $owner[2]" }
      if (( $#perms )) { chmod $perms[2] $dir; print "chmod: $dir $perms[2]" }
    }
  }
}

configs=${1:-/Users/ko/projects/configs}
configs_owner=$(stat -f '%Su:%Sg' -- $configs)
home=/Users/${configs_owner%%:*}

# define dirs
dirs_user_space=(
  .cache/homebrew
  .config
  .local/{bin,share}
  .local/state{,/asdf,/homebrew,/log,/vim/undo,/zsh,/zsh/completions}
  ScreenCapture
)
dirs_user_space=( $home/${^dirs_user_space} )

dirs_system_space=(
  /var/log/{grafana,jaeger,loki,prometheus,dir_size_exporter,port_exporter,otelcol}
  /usr/local/var/{grafana,prometheus,dir_size_exporter}
)

dirs_system_space_world=(
  /var/custom/cache/s-rt-get-term-open-files-with
)


# create dirs
mk_dirs --owner $configs_owner $dirs_user_space
mk_dirs --owner root:${configs_owner#*:} --perms 2775 $dirs_system_space
mk_dirs --perms 1777 $dirs_system_space_world
