#!/bin/zsh
#>[≟]
#   1. search for all *.repo.auto.tmpl templates under templates/
#   2. render it to the repo path in its render-to: frontmatter
#/[≟]

emulate -LR zsh
IFS=
setopt errexit pipefail
autoload -Uz log-msg

configs=${1:-/Users/ko/projects/configs}

function strip-frontmatter-if-empty {
  local content=$(<&0)
  local -a lines=( ${(f)content} ) #[≟] f - replace newlines with \n

  local empty_frontmatter=$'---\n{}\n---'
  local head=${(F)lines[1,3]} #[≟] F - replace \n with newlines

  if [[ $head == $empty_frontmatter ]] content=${(F)lines[4,-1]}
  print -r -- $content
}

function render_template {
  local template=$1
  local render_to

  # 1. read render-to from frontmatter
  render_to=$(yq -f extract '.render-to' $template)

  # 2. render template cleaning frontmatter on the fly
  yq -f process 'del(.render-to)' $template \
    | strip-frontmatter-if-empty \
    | gomplate --chmod 0660 -o $configs/$render_to ; log-msg -t gomplate -- $configs/$render_to
}

pushd $configs
#[≟] . - regular files, D - GLOB_DOT opt (search hidden)
for template ( templates/**/*.repo.auto.tmpl(.D) ) {
  render_template $template
}
popd
