#!/bin/zsh
#>[≟]
#   1. search for all *.host.auto.tmpl templates
#   2. render it on the host
#/[≟]

emulate -LR zsh
IFS=
setopt errexit
autoload -Uz log-msg

configs=${1:-/Users/ko/projects/configs}
t_ext='.host.auto.tmpl'

pushd $configs/root-ln

#[≟] . - regular files, D - GLOB_DOT opt (search hidden)
for template ( **/*${t_ext}(.D) ) {
  #[≟] % - strip non greedy from the end
  render_to=/${template%${t_ext}}
  gomplate -f "$template" -o "$render_to" ; log-msg -t gomplate -- $render_to
}

popd
