#!/usr/bin/env zsh
#>[what]
#   Suggest commit message via LLM.
#   Usage: <extra-instructions-on-stdin> | llm-git-commit-suggest [diff-base]
#   stdin: optional extra instructions.
#   diff-base: optional commit to diff staged against (default HEAD), e.g. HEAD~1 for amend.
#   provider, model, template, env from /etc/custom/llm.yml.
#   Upstream: git-commit-upsert. Out: { "subject": ..., "description": ... }.
#/[what]

set -e

source "${0:A:h}/lib/llm-lib.zsh"
read -r llm_script llm_model llm_template <<<"$(lib-llm-config-load "${0:t}")"
lib-llm-env-export "${0:t}"
autoload -Uz fn-log-msg


##[>] script input
typeset -A script_input=(
  in_instructions_runtime "$([[ -t 0 ]] || cat)"
)
typeset -a diff_base=(${1:+$1})
##[<] script input


##[>] template input 🤖
get_current_branch() { local b=$(git rev-parse --abbrev-ref HEAD); [[ $b == main ]] || echo $b }
get_commit_template() {
  local f=$(git config --get commit.template); f=${f/#\~/$HOME}
  [[ -n $f && -f $f ]] && cat "$f"
}
get_autogen_files() {
  local f
  for f (${(f)"$(git diff --cached $diff_base --name-only)"}) {
    [[ "$(git show ":$f" 2>/dev/null | head -1)" == *"autogenerated using "*.ontoRepo.tpl* ]] && print -r -- $f
  }
  true
}

typeset -a autogen_files exclude_specs
autogen_files=(${(f)"$(get_autogen_files)"})
if (( $#autogen_files )) exclude_specs=(":(exclude)"${^autogen_files})

typeset -A template_input=(
  CURRENT_BRANCH "$(get_current_branch)"
  COMMIT_TEMPLATE "$(get_commit_template)"
  DIFF_FULL "$(git diff --cached $diff_base -- . $exclude_specs)"
  DIFF_STATS "$(git diff --cached $diff_base --stat -- . $exclude_specs)"
  FILES_AUTOGENERATED "${(F)autogen_files}"
  INSTRUCTIONS_RUNTIME "$script_input[in_instructions_runtime]"
)
if [[ -z $template_input[DIFF_FULL] ]] {
  template_input[DIFF_FULL]="$(git diff --cached $diff_base)"
  template_input[DIFF_STATS]="$(git diff --cached $diff_base --stat)"
  template_input[FILES_AUTOGENERATED]=""
}
##[<] template input 🤖


[[ -n $template_input[DIFF_FULL] ]] || { echo "error: nothing staged" >&2; exit 1 }
fn-log-msg -t "${0:t}" "model $llm_model, branch ${template_input[CURRENT_BRANCH]:-none}, staged diff ${#template_input[DIFF_FULL]} chars" >&2

##[>] fill template 🤖
prompt=$(lib-llm-prompt-fill "$llm_template" template_input)
fn-log-msg -t "${0:t}" "prompt: ${#prompt} chars, calling llm ..." >&2
##[<] fill template 🤖


##[>] llm invocation
schema='{
  "type": "object",
  "properties": {
    "subject": { "type": "string" },
    "description": { "type": "string" }
  },
  "required": ["subject", "description"],
  "additionalProperties": false
}'

out=$(<<< "$prompt" "$llm_script" --model "$llm_model" --schema "$schema")
fn-log-msg -t "${0:t}" "llm returned ${#out} chars" >&2
print -r -- "$out"
##[<] llm invocation
