#!/usr/bin/env zsh
#>[what]
#   LLM driven change request (MR/PR) generation
#   Usage: <extra-instructions-on-stdin> | llm-git-mr-suggest [--range <range>]
#   extra-instructions: optional, from stdin when piped.
#   provider, model, template, env resolved from /etc/custom/llm.yml.
#   Upstream: git-mr-upsert. Downstream: llm run script from llm.yml.
#   In: commit messages, diff stats + current MR/PR body as context.
#   Out: { "title": ..., "description": ... }. description top: tool-injected ## Commits list.
#/[what]

set -e

source "${0:A:h}/lib/llm-lib.zsh"
read -r llm_script llm_model llm_template <<<"$(lib-llm-config-load "${0:t}")"
lib-llm-env-export "${0:t}"
autoload -Uz fn-log-msg


##[>] script input
zparseopts -D -E -- -range:=opt_range
typeset -A script_input=(
  in_instructions_runtime "$([[ -t 0 ]] || cat)"

  opt_range "${opt_range[2]:-main..$(git rev-parse --abbrev-ref HEAD)}"
)
##[<] script input

fn-log-msg -t "${0:t}" "range $script_input[opt_range], model $llm_model" >&2

[[ -n "$(git log --format=%h "$script_input[opt_range]")" ]] || { echo "error: no commits in $script_input[opt_range]" >&2; exit 1 }


##[>] current mr/pr description 🤖
case "$(git remote get-url origin)" in
  *gitlab.com*) current_description="$(glab mr view -F json --jq .description 2>/dev/null || true)" ;;
  *github.com*) current_description="$(gh pr view --json body --jq .body 2>/dev/null || true)" ;;
  *) current_description="" ;;
esac
fn-log-msg -t "${0:t}" "current description: ${#current_description} chars" >&2
##[<] current mr/pr description 🤖


##[>] commit list (deterministic, newest-first) 🤖
commit_list="$(git log --format='- %s' "$script_input[opt_range]")"
fn-log-msg -t "${0:t}" "commits:"$'\n'"$commit_list" >&2
##[<] commit list (deterministic, newest-first) 🤖


##[>] autogenerated files exclusion 🤖🤖
get_autogen_files() {
  local head=${script_input[opt_range]#*..} f
  for f (${(f)"$(git diff --name-only "${script_input[opt_range]/../...}")"}) {
    [[ "$(git show "$head:$f" 2>/dev/null | head -1)" == *"autogenerated using "*.ontoRepo.tpl* ]] && print -r -- $f
  }
  true
}

typeset -a autogen_files exclude_pathspecs
autogen_files=(${(f)"$(get_autogen_files)"})
if (( $#autogen_files )) exclude_pathspecs=(":(exclude)"${^autogen_files})
##[<] autogenerated files exclusion 🤖🤖


##[>] template vars 🤖
typeset -A template_vars=(
  COMMIT_BODIES "$(git log --format='%B' "$script_input[opt_range]")"
  DIFF_STATS "$(git diff --stat "${script_input[opt_range]/../...}" -- . $exclude_pathspecs)"
  FILES_AUTOGENERATED "${(F)autogen_files}"
  CURRENT_DESCRIPTION "$current_description"
  INSTRUCTIONS_RUNTIME "$script_input[in_instructions_runtime]"
)
##[<] template vars 🤖


##[>] render prompt 🤖
prompt=$(lib-llm-prompt-render "$llm_template" template_vars)
fn-log-msg -t "${0:t}" "prompt: ${#prompt} chars, calling llm ..." >&2
##[<] render prompt 🤖


##[>] llm invocation
schema='{
  "type": "object",
  "properties": {
    "title": { "type": "string" },
    "description": { "type": "string" }
  },
  "required": ["title", "description"],
  "additionalProperties": false
}'

out=$(<<< "$prompt" "$llm_script" --model "$llm_model" --schema "$schema")
fn-log-msg -t "${0:t}" "llm returned ${#out} chars, injecting commit list" >&2
##[<] llm invocation


##[>] inject commit list at top of description 🤖
commits_block=$'## Commits\n'"$commit_list"
jq --arg c "$commits_block" '.description = $c + "\n\n## Changes\n\n" + .description' <<< "$out"
fn-log-msg -t "${0:t}" "done" >&2
##[<] inject commit list at top of description 🤖
