unbind-key -T root -a
unbind-key -T prefix -a
unbind-key -T copy-mode -a
unbind-key -T copy-mode-vi -a

set -g status on
set -g status-interval 1
set -g status-position top

set -g status-right "#(date '+%a | %H:%M ')"
set -g status-right-length 40
set -g status-style "bg=#b8b8b8,fg=#2a2a2a"

set -g status-left "#[fg=#555555]#S #[fg=#888888]│ "
set -g status-left-length 40

setw -g window-status-style "bg=#b8b8b8,fg=#2a2a2a"
setw -g window-status-format "#W"
setw -g window-status-current-style "bg=#b8b8b8,fg=#000000,bold"
setw -g window-status-current-format "#[fg=#000000,bold]#W#[default]"
setw -g window-status-current-format "#[bold]#W#[nobold]"
setw -g window-status-separator " | "

set -g status-left-style "bg=#b8b8b8,fg=#2a2a2a"
set -g status-right-style "bg=#b8b8b8,fg=#2a2a2a"

set -g pane-border-style "fg=#888888" 
set -g pane-active-border-style "fg=#1a1a1a,bold" 
set -g pane-border-status bottom
set -g pane-border-format "#[align=right]#{?pane_active,#[fg=#000000#],#[fg=#707070]}#{pane_current_path} "

set -g message-style "bg=#b8b8b8,fg=#000000,bold"


# cmd + t - new pane
bind-key -T prefix t \
    split-window -v -c "#{pane_current_path}" \; \
    select-layout main-vertical

# cmd + w - close pane
bind-key -T prefix w confirm-before -p "kill pane #P? (y/n)" kill-pane

# cmd + alt + arrows - navigation
bind-key -T prefix Right select-pane -R
bind-key -T prefix Left  select-pane -L
bind-key -T prefix Down  select-pane -D
bind-key -T prefix Up    select-pane -U

# zoom pane - cmd + alt + =
bind-key -T prefix p resize-pane -x '85%' -y '85%'

# zoom out pane - cmd + alt + -
bind-key -T prefix m select-layout main-vertical
