##[>] 🤖🤖
defaults:
  email: odwrotkonrad@gmail.com
  algorithm: ecdsa-sha2-nistp521

rotation:
  - type: access
    period: 3 months
    scope: global
  - type: signing
    period: 3 months
    scope: global

keys:
  id_access:
    type: access
    publishTo:
      - gitlab
      - github
  id_signing:
    type: signing
    publishTo:
      - gitlab
      - github
##[<] 🤖🤖
