#!/bin/zsh

emulate -LR zsh
set -e

#[…] 🤖🤖
brew bundle install

installers=(
    s-rt-install-asdf
    s-rt-install-aws-cli
    s-rt-install-gcloud-cli
    s-rt-install-kitty
    s-rt-install-jaeger
    s-rt-install-ollama
    s-rt-install-otel-collector
    s-rt-install-prometheus
)
for installer in ${installers}; ${installer}

#[≟] other language-level tools
pip install -r /etc/python/requirements.txt
gem install ruby-lsp
#[⫶] 🤖🤖
