#!/bin/sh

set -e

go install golang.org/x/tools/gopls@latest

go install github.com/hairyhenderson/gomplate/v4/cmd/gomplate@latest

go install github.com/evilmartians/lefthook/v2@latest

npm install -g pyright typescript-language-server typescript

gem install ruby-lsp
