#!/bin/zsh
#>[what]
#   generate zsh completion files
#/[what]

emulate -LR zsh
setopt errexit
umask 002

rg --generate=complete-zsh > /etc/zsh/zshrc.d/completions/_rg
asdf completion zsh > "${ZDOTDIR}/zshrc.d/completions/_asdf"
