#!/bin/zsh
#>[≟]
#   install aws cli v2 per os/arch via is-os/is-arch predicates
#/[≟]

emulate -LR zsh
set -e

tmp=$(mktemp -d)
cd "$tmp"

if { is-os mac } {
    curl "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "AWSCLIV2.pkg"
    sudo installer -pkg AWSCLIV2.pkg -target /
    exit-with 0
}


if { ! is-os linux } exit-with 1 "unknown system: $(uname -s)"

case $(uname -m) {
    (arm64|aarch64) arch=aarch64 ;;
    (x86_64|amd64)  arch=x86_64 ;;
    (*) exit-with 1 "unknown arch: $(uname -m)" ;;
}

curl "https://awscli.amazonaws.com/awscli-exe-linux-${arch}.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install --update
