##[>] 🤖🤖
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4327
      http:
        endpoint: localhost:4328
  jaeger:
    protocols:
      grpc:
        endpoint: localhost:14250
      thrift_http:
        endpoint: localhost:14268
  zipkin:
    endpoint: localhost:9411

processors:
  batch: {}

extensions:
  jaeger_storage:
    backends:
      mem:
        memory:
          max_traces: 100000
  jaeger_query:
    storage:
      traces: mem
    http:
      endpoint: localhost:16686
    grpc:
      endpoint: localhost:16685
  healthcheckv2:
    use_v2: true
    http:
      endpoint: localhost:13134
  pprof:
    endpoint: localhost:1777

exporters:
  jaeger_storage_exporter:
    trace_storage: mem

service:
  extensions: [jaeger_storage, jaeger_query, healthcheckv2, pprof]
  pipelines:
    traces:
      receivers: [otlp, jaeger, zipkin]
      processors: [batch]
      exporters: [jaeger_storage_exporter]
  telemetry:
    resource:
      service.name: jaeger
    metrics:
      level: detailed
      readers:
        - pull:
            exporter:
              prometheus:
                host: localhost
                port: 8890
    logs:
      level: info
##[<] 🤖🤖
